### ISSUE TITLE
2021-07-24 dail logs

### ISSUE THREAD

**Issue by Gyoung-min** [Gyoung-min/javaStudy#82]
## 오늘 학습한 내용
<SQL 기본 문법>
- 테이블 생성
  - CREATE TABLE 테이블 명 (컬럼명 자료형....);
    - 자료형
      - NUMBER : 수치형 데이터
      -  CHAR : 고정 문자열
      - VARCHAR2 : 가변길이 문자열

- 테이블 검색
  - SELECT * FROM 테이블 명;

- 테이블 값 대입
  - INSERT INTO 테이블 명(칼럼 명1, 칼럼 명2...) VALUES (값1, 값2...);

- 검색
  - SELECT 컬럼이름 FROM 테이블 명;
  - 모든 컬럼 검색 시 (*)를 사용

- 삭제
  - DELETE FROM 테이블 명(조건);
  - DELETE FROM 테이블 명 WHERE 컬럼명 = ?;
 
- 변경
  - UPDATE 테이블 명 SET 컬럼이름 = 값, 컬럼이름 = 값 ... WHERE 조건;

- 삭제
  - DROP TABLE 테이블 명;

- 전체 저장
  - COMMIT;

## 회고
commit을 하지 않으면 이클립스에서 명령어가 제대로 수행되지 않을 수 있으니 주의하자!

**Comment by lette1394** [comment]
@Gyoung-min 
많이 안쓰면 까먹습니다;
저도 많이 안써서 까먹어요...

자주 써볼일은 없을 거 같으니, 이런 문법들이 있고 이걸 찾아서 쓸 수 있는 정도만 공부하시면 됩니다.
고생하셨습니다

**Comment by lette1394** [comment]
> commit을 하지 않으면 이클립스에서 명령어가 제대로 수행되지 않을 수 있으니 주의하자!

이걸 왜 하는지, 이걸 하지 않으면 왜 제대로 수행되지 않는지 상세히 조사해주세요 (중요)
hint: `database transaction`

**Comment by lette1394** [comment]
@Gyoung-min

**Comment by Gyoung-min** [comment]
## Commit (Transaction)

1. 트랜잭션(Transaction)
  - 트랜잭션이란 질의(query)를 하나의 묶음 처리해서 만약 중간에 실행이 중단되었을 경우, 처음부터 다시 실행하는 Rollback을 수행하고, 오류없이 실행을 마치면 commit을 하는 실행단위를 의미한다.
  - 즉, 한 번 질의가 실행되면 질의가 모두 수행되거나 모두 수행되지 않는 작업 수행의 논리적 단위이다.
  - DBMS의 성능은 초당 트랜잭션의 실행 수(TPS)로 측정한다

  **트랜잭션의 사용 이유**
  
   - 트랜잭션은 DB 서버에 여러 개의 클라이언트가 동시에 액세스 하거나 응용프로그램이 갱신을 처리하는 과정에서 중단될 수 있는 경우 등 데이터 부정합을 방지하고자 할 때 사용한다.
   - 부정합이 발생하지 않으려면 프로세스를 병렬로 처리하지 않도록 하여 한 번에 하나의 프로세스만 처리하도록 하면 되는데, 이는 효율이 좋지 않다
   - 즉, 병렬로 처리할 수 밖에 없는 현실적인 상황으로 인해 부정합을 방지하고자 트랜잭션을 사용하는 것이다.

2. 특징(ACID)
  - 원자성 ( Atomicity )
    - 트랜잭션의 작업이 부분적으로 실행되거나 중단되지 않는 것을 보장
    - ALL or Notiong의 개념으로 작업 단위를 일부분만 실행하지 않는다는 것을 의미
  - 일관성 ( Consistency )
    - 트랜잭션이 성공적으로 완료되면 일관적인 DB상태를 유지하는 것을 의미
    - EX) 타입의 일치
  - 격리성 ( Isolation )
    - 트랜잭션 수행 시 다른 트랜잭션의 작업이 끼어들지 못하도록 보장하는 것
    - 트랜잭션 끼리는 서로 간섭할 수 없다
  - 지속성 ( Durability )
    - 성공적으로 수행된 트랜잭션은 영원히 반영이 되는 것
    - commit을 하면 현재 상태는 영원히 보장된다.

3. Commit, Rollback, Savepoint
  - Commit
    - commit 전에는 단지 메모리 Buffer에만 영향을 받았기 때문에, 데이터의 변경 이전 상태로 복구 가능 -> commit 후에는 변경사항이 DB에 반영되며 이전 데이터는 영원히 잃어버리게 된다
    - 현재 사용자는 Select 문장으로 결과를 확인 가능
    - commit 이전에, 다른 사용자는 현재 사용자가 수행한 명령의 결과로 볼 수 없다. -> commit 이후에 모든 사용자가 결과 확인 가능
    - commit 이전에, 변경된 행은 잠금이 설정되어서 다른 사용자가 변경할 수 없다 -> commit 이후에 잠금이 풀리고 다른 사용자들이 행을 조작함
    - 어플리케이션의 정상적인 종료 or 이상 종료되어 DB 접속이 단절되었을 때는 자동으로 Rollback
  - Rollback
    - 테이블 내 입력한 데이터나, 수정한 데이터, 삭제한 데이터에 대하여 Commit 이전에는 변경 사항을 취소할 수 있는데 데이터페이스에서는 롤백 기능을 사용하면 된다. 롤백은 데이터 변경 사항이 취소되어 데이터의 이전 상태로 복구되며 관련된 행에 대한 잠금이 풀리고 다른 사용자들이 데이터 변경을 할 수 있게 됨을 의미
  - Savepoint
    - 저장점(Savepoint)을 정의하면 롤백(Rollback)할 때 트랜잭션에 포함된 전체 작업을 롤백하는 것이 아니라 현 시점에서 Savepoint까지 트랜잭션의 일부만 롤백할 수 있다. 따라서 복잡한 대규모 트랜잭션에서 에러가 발생할 때 Savepoint까지의 트랜잭션만 롤백하고 실패한 부분에 대해서만 다시 실행할 수 있다.

**Comment by lette1394** [comment]
@Gyoung-min 

- 트랜잭션은 반드시 database에 대한 내용만은 아닙니다. 다양한 곳에서 사용하고 있는 개념이고, 직접(!) 구현하기도 해요
- 트랜잭션 격리 수준에 대해서도 조사해주세요 (Transaction Isolation Level)
- (심화) 트랜잭션을 어떻게 구현했는지에 대해서도 조사해주세요
